### ISSUE TITLE
Having an issue with discovery.

### ISSUE THREAD

**Issue by CaptainKhan** [DylanVanAssche/harbour-sailfinder#130]
I deleted the app, reinstalled same issue. 

Contact card continuously refreshes and is somehow stuck where i cant change the search radius or age, its greyed out.

In the discovery card the percentage still runs through and it seems to work when liking or unliking matches.

Is discovery somehow linked to having GPS on? Would it be possible to add a feature to manually enter country and city?

Would it be possible from within the UI to logout and clear cache?

Cheers

**Comment by DylanVanAssche** [comment]
I'm sorry you're having some issues with Sailfinder.
I have also a discovery issue, reported by other people.
Currently Sailfinder is not updated anymore because I'm moving all my apps to a C++ backend, including Sailfinder.

Sailfinder will be updated with a refreshed API and improved stability as soon as BeRail and Sailbook are ported to C++

**Comment by DylanVanAssche** [comment]
Manually entering the location is possible however, Jolla won't allow me to use QtLocation to show a map. That's the reason why I didn't add this feature already. As soon as Jolla allows it, I can do that.

**Comment by CaptainKhan** [comment]
Hey Dylan thanks for letting me know, looking forward to future releases!

**Comment by CaptainKhan** [comment]
I was actually able to resolve it by adding sex, and interested in then distance, after toggling discovery.

**Comment by DylanVanAssche** [comment]
Oh nice to know :)
